-- Merge trainers + students into one users table with a role column.
-- See docs/specs/user-unification/spec.md section 4.

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    cpf            VARCHAR(11)  NOT NULL,
    cref           VARCHAR(20),
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_cpf UNIQUE (cpf)
);

-- Trainers keep their original id: training_plans.trainer_id has a live FK to trainers(id) with
-- real data, and must keep resolving after trainers is dropped below.
INSERT INTO users (id, name, email, cpf, cref, password_hash, role)
SELECT id, name, email, cpf, cref, password_hash, 'TRAINER' FROM trainers;

SELECT setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 1));

-- Students get fresh ids: nothing references students.id today.
INSERT INTO users (name, email, cpf, password_hash, role)
SELECT name, email, cpf, password_hash, 'CLIENT' FROM students;

ALTER TABLE training_plans DROP CONSTRAINT fk_training_plans_trainer;
ALTER TABLE training_plans ADD CONSTRAINT fk_training_plans_trainer FOREIGN KEY (trainer_id) REFERENCES users (id);

DROP TABLE trainers;
DROP TABLE students;
