CREATE TABLE trainers (
    id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    CONSTRAINT uq_trainers_email UNIQUE (email)
);
