syntax = "proto3";

package vertice.trainer.v1;

import "google/protobuf/empty.proto";

option java_package = "com.vertice.api.generated.grpc.trainer.v1";
option java_multiple_files = true;

service TrainerService {
  rpc ListTrainers(ListTrainersRequest) returns (ListTrainersResponse);
  rpc GetTrainer(GetTrainerRequest) returns (TrainerResponse);
  rpc CreateTrainer(TrainerCreateRequest) returns (TrainerResponse);
  rpc UpdateTrainer(UpdateTrainerRequest) returns (TrainerResponse);
  rpc DeleteTrainer(DeleteTrainerRequest) returns (google.protobuf.Empty);
  rpc SetTrainerPassword(SetTrainerPasswordRequest) returns (google.protobuf.Empty);
}

message TrainerResponse {
  int64 id = 1;
  string name = 2;
  string email = 3;
  string cpf = 4;
}

message TrainerRequest {
  string name = 1;
  string email = 2;
  string cpf = 3;
}

message TrainerCreateRequest {
  string name = 1;
  string email = 2;
  string password = 3;
  string cpf = 4;
}

message ListTrainersRequest {
}

message ListTrainersResponse {
  repeated TrainerResponse trainers = 1;
}

message GetTrainerRequest {
  int64 id = 1;
}

message UpdateTrainerRequest {
  int64 id = 1;
  TrainerRequest trainer = 2;
}

message DeleteTrainerRequest {
  int64 id = 1;
}

message SetTrainerPasswordRequest {
  int64 id = 1;
  string password = 2;
}
